// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU-jHTn3NRO3T8ykwZ8UVEvkVFClDW-HY',
    appId: '1:896289309972:android:72a4ffb4e225be95cc6e01',
    messagingSenderId: '896289309972',
    projectId: 'habit-forge-bba74',
    storageBucket: 'habit-forge-bba74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhLi_aLk8_UV_lAp1vBAaM5beF2IsV_S0',
    appId: '1:896289309972:ios:9e805439d38d22c6cc6e01',
    messagingSenderId: '896289309972',
    projectId: 'habit-forge-bba74',
    storageBucket: 'habit-forge-bba74.firebasestorage.app',
    iosBundleId: 'com.example.habitForge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhLi_aLk8_UV_lAp1vBAaM5beF2IsV_S0',
    appId: '1:896289309972:ios:9e805439d38d22c6cc6e01',
    messagingSenderId: '896289309972',
    projectId: 'habit-forge-bba74',
    storageBucket: 'habit-forge-bba74.firebasestorage.app',
    iosBundleId: 'com.example.habitForge',
  );
}
